import type { JokerId } from "./types";

/** Artwork supplied for every MOD. The path is keyed by the game id, not by UI copy. */
export const JOKER_ART: Readonly<Record<JokerId, string>> = {
  "zero-day": "/art/special-cards/zero-day.png",
  redline: "/art/special-cards/redline.png",
  "blue-buffer": "/art/special-cards/blue-buffer.png",
  "green-loop": "/art/special-cards/green-loop.png",
  "yellow-ticket": "/art/special-cards/yellow-ticket.png",
  "odd-signal": "/art/special-cards/odd-signal.png",
  "even-signal": "/art/special-cards/even-signal.png",
  "cache-hit": "/art/special-cards/cache-hit.png",
  "splash-mode": "/art/special-cards/splash-mode.png",
  "spectrum-analyzer": "/art/special-cards/spectrum-analyzer.png",
  "monochrome-monitor": "/art/special-cards/monochrome-monitor.png",
  "sequence-accelerator": "/art/special-cards/sequence-accelerator.png",
  "full-stack": "/art/special-cards/full-stack.png",
  "spare-battery": "/art/special-cards/spare-battery.png",
  "last-commit": "/art/special-cards/last-commit.png",
  "version-control": "/art/special-cards/version-control.png",
  "cmyk-core": "/art/special-cards/cmyk-core.png",
  "combo-compiler": "/art/special-cards/combo-compiler.png",
  "hot-swap": "/art/special-cards/hot-swap.png",
  "null-pointer": "/art/special-cards/null-pointer.png",
  "venom-drip": "/art/special-cards/venom-drip.png",
  "volt-surge": "/art/special-cards/volt-surge.png",
  "half-compile": "/art/special-cards/half-compile.png",
  "ice-cream-cache": "/art/special-cards/ice-cream-cache.png",
  "memory-buffer": "/art/special-cards/memory-buffer.png",
  "mystic-summit": "/art/special-cards/mystic-summit.png",
  "delayed-gratification": "/art/special-cards/delayed-gratification.png",
  "fibonacci-routine": "/art/special-cards/fibonacci-routine.png",
  "loyalty-session": "/art/special-cards/loyalty-session.png",
  "jolly-routine": "/art/special-cards/jolly-routine.png",
  "zany-core": "/art/special-cards/zany-core.png",
  "mad-routine": "/art/special-cards/mad-routine.png",
  "runner-process": "/art/special-cards/runner-process.png",
  "green-demon": "/art/special-cards/green-demon.png",
  "eight-ball-exploit": "/art/special-cards/eight-ball-exploit.png",
  "bloodstone-driver": "/art/special-cards/bloodstone-driver.png",
  "reserved-slot": "/art/special-cards/reserved-slot.png",
  "turtle-bean-cache": "/art/special-cards/turtle-bean-cache.png",
  "spare-trousers": "/art/special-cards/spare-trousers.png",
  "blueprint-protocol": "/art/special-cards/blueprint-protocol.png",
  "cavendish-overclock": "/art/special-cards/cavendish-overclock.png",
  "perkeos-echo": "/art/special-cards/perkeos-echo.png",
  "stencil-core": "/art/special-cards/stencil-core.png",
};

/** MAYHEM cards share a single visual regardless of their player-authored rule. */
export const MAYHEM_CARD_ART = "/art/special-cards/mayhem.png";
